name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please describe the problem and your proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve? What use case are you trying to support?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered or tried?

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of gatekeeper does this relate to?
      options:
        - Policy engine
        - Approval workflow
        - Audit logging
        - Memory / Knowledge Graph
        - Client library
        - Shell / File / HTTP tools
        - Documentation
        - Other
    validations:
      required: true
